name: Deploy Compodoc to GitHub Pages

on:
  push:
    branches:
      - dev  # Change to your default branch if needed

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: go to source directory
        run: cd ./Skarabeus_Ui
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Adjust if needed

      - name: Install dependencies
        run: npm install  # Ensures clean install

      - name: Generate documentation
        run: npx compodoc -p tsconfig.compodoc.json -d docs --silent

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: dev
          folder: docs  # Must match the output directory used in the Compodoc command
