name: Deploy Compodoc to GitHub Pages

on:
  push:
    branches:
      - dev  # Change to your default branch if needed

permissions:
  actions: read
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Adjust if needed

      - name: Install dependencies
        run: |
          cd ./Skarabeus_Ui
          npm install 

      - name: Generate documentation
        run: |
          cd ./Skarabeus_Ui
          npx compodoc -p tsconfig.compodoc.json -d ../docs --disableCoverage --customLogo ./src/assets/skarabeus_logo_small.png --customFavicon ./src/assets/skarabeus_logo.png --silent
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
        # Upload entire repository
          path: './docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
